---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

Download data from google spreadsheets.
###########
#	INPUT:	- Step 1, download .csv from Google.
#         - put .csv  ./data_raw
#         - ALL years, all lab data 
#					- OK to overwrite data in ./data_raw, with newer.
#
#	OUTPUT:	
#
###########

###########
#	read ALL on ...		
# 	raw data from local into tibble
###########

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  comment="      ##",  error=TRUE, collapse=TRUE)
```

```{r library, include=FALSE		}
library(jimTools)
library(here)
library(tidyverse)
```


```{r render, eval=FALSE	}
here()
file <- "/home/jim/code/r_rafael/rmd/005_linear_algebra_examples.Rmd"
file  <- basename(file)
dir="rmd"

jimTools::ren_pdf(file,dir)
jimTools::ren_github(file, dir)
```



```{r read_raw}
read_raw_data  <- function(){
# cols_only() --  to read specified cols (omitting others)
    # IF lazy,  use col_types=cols( .default=col_guess())
    # cols(),   to read every col
    # type is list obj

# parse dates 09APR2010
type <- cols_only(Date = col_date(format="%d%b%Y"),   
						      Test_Name="c",
						      Test_Result="n")  
# READ
# input_data  <- "ALL_lab_data.csv"
input_data  <- "2020_07_26_ALL_lab_data.csv"

result_ALL<-read_csv( file= paste0("data_raw/",input_data),
        na = c("NA", "N/A"),  # these entries remain numbers
        col_names = TRUE,  # use 1st line,
        col_types = type
    )   
}

```
```{r clean_data}

clean_raw_data  <- function(t=NULL ){
# CLEAN
t   <- t  %>% 
  dplyr::select(Date,Test_Name, Test_Result) %>% 
    dplyr::arrange(Date)
}

```
```{r write_data_clean}

write_raw_clean_data  <- function(t=NULL){
# WRITE
output_data  <- "ALL_lab_data.csv"
write_csv(t, paste0("./data_clean/", output_data ))
}

```
```{r do_it}
result_ALL  <- read_raw_data()
result_ALL  <- clean_raw_data(result_ALL)
write_raw_clean_data(result_ALL)
head(result_ALL)
```



```{r knit_exit()}
knitr::knit_exit()
```

***
