---
title: Template for .Rmd
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---
005_plots.Rmd

```{r setup, include=FALSE		}
knitr::opts_chunk$set(
											echo = TRUE,  
											comment="      ##",  
											error=TRUE, 
											collapse=TRUE)
```

```{r library, include=FALSE		}
library(jimTools)
library(here)
library(tidyverse)
library(lubridate)   # ymd requires
```
<!-- RENDER?   SEE BOTTOM -->

read saved data
```{r read_data}
result <- readr::read_csv(here("data_clean", "ALL_lab_data.csv"))
```

before plots, check the data
```{r check_data}
# summarize,  Count for each Test (in alpha order)
result %>% 
	group_by(Test_Name) %>% 
	summarize(count = n()) %>% 
	arrange(Test_Name) %>% 
	print(n=50)
```
plot GLU
```{r plot_GlU}
z <- result %>% filter(Test_Name== "GLU")
g <- ggplot(z, aes(x=Date,y=Test_Result)) +
	     geom_point() +
       scale_x_date(date_labels = "%Y") +
       geom_hline(yintercept = 100, color="red") +
       labs (title = "Fasting Glucose",
          subtitle = "2008 - 2020") +
	     geom_vline(data = tibble(    # adding layer!, own data
				x= ymd(c("2012-01-01","2016-05-01"))
				),
				mapping = aes(xintercept = as.numeric(x)),
				color = "blue",
				linetype= 2)   # dotted
            
g
summary(g)

```


plot eGFR
```{r plot_eGFR}
g <-filter(result, Test_Name == "eGFR") %>% 
    ggplot(aes(x=Date, y=Test_Result)) +
		geom_point()
g
```

\newpage


Data for:   UrineOxalate 24 hour 
```{r table_urine_oxalate, echo=FALSE	}
ur_ox_tibble  <- 
	filter(result, Test_Name == "Ur_Ox24" )
ur_ox_tibble
```
\newpage


```{r plot_urOx, echo=FALSE		}
# filter uses single &  ;   not &&. 
ur_ox_tibble  <- 
	filter(result, Test_Name == "Ur_Ox24" & Test_Result < 500)

g <-filter(result, Test_Name == "Ur_Ox24" & Test_Result < 500) %>% 
    ggplot(aes(x=Date, y=Test_Result)) + geom_point() +
    		labs (title = "Ur_Ox24", subtitle = "2008 - 2020") 

#g  <- g + geom_jitter()

g  <- g + geom_hline(aes(yintercept=35,  color="red"))

g 

# ggsave(
#     "~/Downloads/print_and_delete/005_simple_lab_plots.png", device="png")
# 
# ggsave(
#     "~/Downloads/print_and_delete/005_simple_lab_plots.bmp", device="bmp")
# 
# ggsave(here("plots", 
#       "005_simple_lab_plots.png"), device="png")
# 
# ggsave(here("plots", "005_simple_lab_plots_Ur_Ox24.bmp"), device="bmp")
# 
```

```{r eval=FALSE	, include=FALSE	}
need?
## save, retrieve, use object - without recalculating

saveRDS(g,file=here("data_intermediate/eGFR.rds"))
g <- readRDS(here("data_intermediate/eGFR.rds"))
g
```


```{r knit_exit}
knitr::knit_exit()
```

need?
```{r next_include_plots, eval=FALSE,	 include=FALSE	 }

g <-  ggplot(result, aes(x=Date, y=Test_Result)) +
    facet_wrap(~Test_Name, nrows=5)

 g + geom_point()

####################
g <-filter(result, Test_Name == "eGFR") %>% 
    ggplot(aes(x=Date, y=Test_Result))
g + geom_point()

g <-filter(result, Test_Name == "Trig") %>% 
    ggplot(aes(x=Date, y=Test_Result))
g + geom_point()

g <-filter(result, Test_Name == "Ur_Oxalate24") %>% 
    ggplot(aes(x=Date, y=Test_Result))
g + geom_point()

g <-filter(result, Test_Name == "GLU") %>% 
    ggplot(aes(x=Date, y=Test_Result))
g + geom_point()

########################
#  WANT this!
#######################

# look at this
# https://stackoverflow.com/questions/41231903/ggplot2-how-to-add-text-to-multiple-vertical-lines-geom-vlines-on-a-time-x-ax?noredirect=1&lq=1

tmp <- data.frame(x=rep(seq(as.Date(0, origin="1970-01-01"),
							length=36, by="1 month"), 2),
				  y=rnorm(72),
				  category=gl(2,36))
p <- ggplot(tmp, aes(x, y, colour=category)) +
	#layer(geom="line") +
	geom_vline(aes(xintercept=as.POSIXct(
		as.Date(c("2016-12-01","2017-02-01")))   ),
			   linetype=4, colour="black")
print(p)
# as.POSIXct(as.Date(c("2016-12-01","2017-02-01")))
```

render
```{r render, eval=FALSE	}
file <- "005_create_plots_lab_tests.Rmd"
file  <- basename(file)
dir="rmd"

jimTools::ren_pdf(file,dir)
#jimTools::ren_github(file, dir)
```
